
jobs:
  include:
      os: osx
      osx_image: xcode11.6
      language: node_js
      node_js: "14"

cache:
  yarn: true
  directories:
    - node_modules

before_install: git pull

script:
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release@17"
  on:
    branch: master
    condition: $TRAVIS_COMMIT_MESSAGE = "release"
